name: Get and Cache Dependencies
description: Get (via npm) and Cache the dependencies
runs:
  using: composite
  steps:
    - name: Cache dependencies
      id: cache
      uses: actions/cache@v3
      with:
        path: node_modules
        key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: npm ci
      ## To use the run key like above in custom action
      ## you need to add the shell key below 
      ## Specify which shell language you are using to execute the steps
      shell: bash 